server:
  port: 8092
spring:
  redis:
    cluster:
      nodes: 192.168.56.10:7001,192.168.56.10:7002,192.168.56.10:7003,192.168.56.10:7004,192.168.56.10:7005,192.168.56.10:7006

  # 这些配置在腾讯云控制台都可查到（使用时替换为你自己的）
  # 腾讯云的SecretId（永久的，可在控制台开启或关闭）
  tencent:
    secretId: AKIDIPHsCF3aqpdAQP7ZkeGdjY6NN6YicGdi
    # 腾讯云的SecretKey（永久的，可在控制台开启或关闭）
    SecretKey: qOffOq1uWrviFVVDetrYx5wWqtfAOKdg
    # 腾讯云的bucket (存储桶)
    bucket: theangel-1306086135
    # 腾讯云的region(bucket所在地区)
    region: ap-guangzhou
    # 腾讯云的allowPrefix(允许上传的路径)
    allowPrefix: '*'
    # 腾讯云的临时密钥时长(单位秒)
    durationSeconds: 10
    # 腾讯云的访问基础链接:
    baseUrl: https://theangel-1306086135.cos.ap-guangzhou.myqcloud.com
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
    alicloud:
      access-key: LTAI5t5Zw9QpcLrfdGCA4NZZ
      secret-key: MEYjLvITV4G6hkv12N41mbrcqR3phk
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: theangel-mall
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 9d04ec7d99b740a9973cf01a438b9337
