spring:
  profiles:
    active: test
  application:
    name: themall-order
  #session保存redis

  session:
    store-type: redis
  #配置redis缓存管理器
  cache:
    type: redis
    # 配置了名字，就只能使用自己的名字
    redis:
      # 存活时间
      time-to-live: 3600000
      #前缀
      #      key-prefix: AUTO-CACHE_
      #是否使用前缀 不使用前缀，开启前缀 会把分区名放前面  分区::名字
      use-key-prefix: true
      #是否缓存空值，解决缓存穿透
      cache-null-values: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    #开启发送端确认，到达rabbitmq
    publisher-confirms: true
    #发送端确认，有没有路由到指定的key  集群是一个副本模式，所有确认才能够确认
    publisher-returns: true
    #    只要抵达队列，以异步发送优先回调我们这个returns
    template:
      mandatory: true
    listener:
      simple:
        #        auto:自动回复    manual:手动确认
        acknowledge-mode: manual

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

