server:
  port: 8087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848

  redis:
    cluster:
      nodes: 192.168.56.10:7001,192.168.56.10:7002,192.168.56.10:7003,192.168.56.10:7004,192.168.56.10:7005,192.168.56.10:7006
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/themall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai

  rabbitmq:
    host: 192.168.56.10
    username: guest
    password: guest
    virtual-host: /themall
    port: 5672
    #开启发送端确认，到达rabbitmq
    publisher-confirms: true
    #发送端确认，有没有路由到指定的key  集群是一个副本模式，所有确认才能够确认
    publisher-returns: true
    #    只要抵达队列，以异步发送优先回调我们这个returns
    template:
      mandatory: true
    listener:
      simple:
        #        auto:自动回复    manual:手动确认
        acknowledge-mode: manual
  thymeleaf:
    cache: false
