spring:
  datasource:
    username: root
    password: hjj0127..
    url: jdbc:mysql://theangel.vip:3306/themall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.56.10
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    #开启发送端确认，到达rabbitmq
    publisher-confirms: true
    #发送端确认，有没有路由到指定的key  集群是一个副本模式，所有确认才能够确认
    publisher-returns: true
    #    只要抵达队列，以异步发送优先回调我们这个returns
    template:
      mandatory: true
    listener:
      simple:
        #        auto:自动回复    manual:手动确认
        acknowledge-mode: manual

  thymeleaf:
    cache: false



