server:
  port: 8080
spring:
  cloud:
    nacos:
      config:
#        namespace: 9e9bfac1-f266-4fc4-b220-2c95997c532b
        extension-configs:
          - dataId: public.yml
            refresh: true
          - dataId: themall-order.yml
            refresh: true
        server-addr: nacos-server.themall:8848
  application:
    name: themall-order
  #session保存redis
  session:
    store-type: redis
  #配置redis缓存管理器
  cache:
    type: redis
    # 配置了名字，就只能使用自己的名字
    redis:
      # 存活时间
      time-to-live: 3600000
      #前缀
      #      key-prefix: AUTO-CACHE_
      #是否使用前缀 不使用前缀，开启前缀 会把分区名放前面  分区::名字
      use-key-prefix: true
      #是否缓存空值，解决缓存穿透
      cache-null-values: true

  datasource:
    username: root
    password: hjj0127..
    url: jdbc:mysql://mysql-master.themall:3306/themall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: rabbitmq.themall
    username: guest
    password: guest
    virtual-host: /themall
    port: 5672
    #开启发送端确认，到达rabbitmq
    publisher-confirms: true
    #发送端确认，有没有路由到指定的key  集群是一个副本模式，所有确认才能够确认
    publisher-returns: true
    #    只要抵达队列，以异步发送优先回调我们这个returns
    template:
      mandatory: true
    listener:
      simple:
        #        auto:自动回复    manual:手动确认
        acknowledge-mode: manual

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

#spring.cloud.alibaba.seata.tx-service-group修改后缀，但是必须和file.conf中的配置保持一致
