server:
  port: 8083
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.10:8858
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  #      config:
  #        extension-configs:
  #          - dataId: public.yml
  #            refresh: true
  #          - dataId: themall-cart.yml
  #            refresh: true
  #        server-addr: nacos-server.themall:8848
  #        username: nacos
  #        password: Poo0054@nacos
  application:
    name: themall-cart

  redis:
    cluster:
      nodes: 192.168.56.10:7001,192.168.56.10:7002,192.168.56.10:7003,192.168.56.10:7004,192.168.56.10:7005,192.168.56.10:7006

  thymeleaf:
    cache: false