server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.themall:8848
      config:
        username: nacos
        password: Poo0054@nacos
        extension-configs:
          - dataId: public.yml
            refresh: true
          - dataId: themall-member.yml
            refresh: true
        server-addr: nacos-server.themall:8848

  redis:
    host: redis.themall
    port: 6379

  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql-master.themall:3306/themall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver