spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    username: root
    password: hjj0127..
    url: jdbc:mysql://theangel.vip:3306/themall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #开发期间 关闭缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

themall:
  thread:
    coreSize: 10
    maxSize: 200
    keepAliveTime: 10

logging:
  level:
    com.theangel.themall: error

