spring:
  profiles:
    active: test
  application:
    name: themall-product

  #session保存redis
  session:
    store-type: redis
    #配置redis缓存管理器
  cache:
    type: redis
    # 配置了名字，就只能使用自己的名字
    redis:
      # 存活时间
      time-to-live: 3600000
      #前缀
      #      key-prefix: AUTO-CACHE_
      #是否使用前缀 不使用前缀但开启前缀 会把分区名放前面  分区::名字
      use-key-prefix: true
      #是否缓存空值，解决缓存穿透
      cache-null-values: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #开发期间 关闭缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

themall:
  thread:
    coreSize: 10
    maxSize: 200
    keepAliveTime: 10
