server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  thymeleaf:
    cache: false

  rabbitmq:
    host: 192.168.56.10
    username: guest
    password: guest
    virtual-host: /themall
    port: 5672
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
    publisher-returns: true

  redis:
    cluster:
      nodes: 192.168.56.10:7001,192.168.56.10:7002,192.168.56.10:7003,192.168.56.10:7004,192.168.56.10:7005,192.168.56.10:7006

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  task:
    execution:
      pool:
        core-size: 20
        maxSize: 50
        queueCapacity: 50

themall:
  thread:
    coreSize: 10
    maxSize: 200
    keepAliveTime: 10

logging:
  level:
    com.theangel.themall: info
