server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.themall:8848
      config:
        username: nacos
        password: Poo0054@nacos
        extension-configs:
          - dataId: public.yml
            refresh: true
          - dataId: themall-search.yml
            refresh: true
        server-addr: nacos-server.themall:8848

  redis:
    host: redis.themall
    port: 6379
