spring:
  redis:
    host: redis.themall
    port: 6379
  zipkin:
    base-url: http://zipkin-server.themall:9411
    locator:
      discovery:
        #关闭服务发现，否则springcloud会把zipkin的url当成服务名称
        enabled: false
    sender:
      #设置http发送数据
      type: web
  sleuth:
    sampler:
      #      设置抽取采集率为100%，默认为10%
      probability: 1
  application:
    name: themall-auth-server
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.themall:8333
    nacos:
      discovery:
        server-addr: nacos-server.themall:8848
        namespace: 9e9bfac1-f266-4fc4-b220-2c95997c532b
#      config:
##        namespace: public
#        server-addr: nacos-server.themall:8848
#        extension-configs:
#          - dataId: public.yml
#            refresh: true
#          - dataId: themall-auth-server.yml
#            refresh: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

  #session保存redis
  session:
    store-type: redis
  #配置redis缓存管理器
  cache:
    type: redis
    # 配置了名字，就只能使用自己的名字
    redis:
      # 存活时间
      time-to-live: 3600000
      #前缀
      #      key-prefix: AUTO-CACHE_
      #是否使用前缀 不使用前缀，开启前缀 会把分区名放前面  分区::名字
      use-key-prefix: true
      #是否缓存空值，解决缓存穿透
      cache-null-values: true

  #开发期间 关闭缓存
  thymeleaf:
#    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.sleuth: error

server:
  port: 8080
  servlet:
    session:
      #session超时时间
      timeout: 30m
