spring:
  #开发期间 关闭缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.theangel.themall: error

server:
  servlet:
    session:
      #session超时时间
      timeout: 30m

