spring:
  redis:
    host: redis.themall
    port: 6379
  zipkin:
    base-url: http://zipkin-server.themall:9411

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.themall:8333
    nacos:
      discovery:
        server-addr: nacos-server.themall:8848
      config:
        server-addr: nacos-server.themall:8848
        extension-configs:
          - dataId: public.yml
            refresh: true
          - dataId: themall-auth-server.yml
            refresh: true
        username: nacos
        password: Poo0054@nacos

  #开发期间 关闭缓存
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework.cloud.openfeign: warn
    org.springframework.sleuth: warn

server:
  port: 8080
  servlet:
    session:
      #session超时时间
      timeout: 30m
