server:
  port: 8085

spring:
  zipkin:
    base-url: http://192.168.56.10:9411
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.10:8858
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
#      config:
#        username: nacos
#        password: Poo0054@nacos
#        server-addr: nacos-server.themall:8848
#        extension-configs:
#          - dataId: themall-gatway.yml
#            refresh: true

logging:
  level:
    org.springframework.cloud.openfeign: info
    org.springframework.sleuth: info



