server:
  port: 88

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: themall-gatway
  zipkin:
    base-url: http://192.168.56.10:9411
    locator:
      discovery:
        #关闭服务发现，否则springcloud会把zipkin的url当成服务名称
        enabled: false

    sender:
      #设置http发送数据
      type: web

  sleuth:
    sampler:
      #      设置抽取采集率为100%，默认为10%
      probability: 1

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    nacos:
      config:
        username: nacos
        password: Poo0054@nacos
        server-addr: theangel.vip:8848
        extension-configs:
          - dataId: themall-gatway.yml
            refresh: true
      discovery:
        server-addr: theangel.vip:8848
    gateway:
      routes:
        #         检索服务
        - id: themall-search
          uri: lb://themall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #          库存服务
        - id: themall-ware
          uri: lb://themall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #          商品优惠服务
        - id: themall-coupon
          uri: lb://themall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         第三方服务
        - id: third-party
          uri: lb://third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         商品服务
        - id: themall-product
          uri: lb://themall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         外网穿透的地址
        - id: themall
          uri: lb://themall-product
          predicates:
            - Path=/themall/**
          filters:
            - RewritePath=/themall/?(?<the>.*), /$\{the}

        #         会员服务
        - id: themall-member
          uri: lb://themall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**,/renren-fast/**
          filters:
            - RewritePath=/api/?(?<the>.*), /renren-fast/$\{the}


        # 商品详情页
        - id: item
          uri: lb://themall-product
          predicates:
            - Host=item.theangel.com
        #            - Path=/item/*.html

        # 商品搜索
        - id: search
          uri: lb://themall-search
          predicates:
            - Host=search.theangel.com
        #            - Path=/list.html

        # 认证
        - id: auth-server
          uri: lb://themall-auth-server
          predicates:
            - Host=auth.theangel.com
        #            - Path=/auth/**

        # 购物车
        - id: themall-cart
          uri: lb://themall-cart
          predicates:
            - Host=cart.theangel.com

        # 订单
        - id: themall-order
          uri: lb://themall-order
          predicates:
            - Host=order.theangel.com

        # 首页
        - id: product-index
          uri: lb://themall-product
          predicates:
            - Host=theangel.com,theangel.vip:8888,127.0.0.1:88,159.75.26.150:8888

        # 用户订单
        - id: member
          uri: lb://themall-member
          predicates:
            - Host=member.theangel.com


        # 秒杀
        - id: themall-seckill
          uri: lb://themall-seckill
          predicates:
            - Host=seckill.theangel.com

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.sleuth: debug



