server:
  port: 88

spring:
  application:
    name: themall-gatway
  cloud:
    gateway:
      routes:
        - id: third-party
          uri: lb://third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        - id: themall-product
          uri: lb://themall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        - id: themall-member
          uri: lb://themall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}



        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<the>.*), /renren-fast/$\{the}
    nacos:
      discovery:
        server-addr: theangel.vip:8848

