server:
  port: 88

spring:
  application:
    name: themall-gatway
  cloud:
    gateway:
      routes:
        #         检索服务
        - id: themall-search
          uri: lb://themall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #          库存服务
        - id: themall-ware
          uri: lb://themall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #          商品优惠服务
        - id: themall-coupon
          uri: lb://themall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         第三方服务
        - id: third-party
          uri: lb://third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         商品服务
        - id: themall-product
          uri: lb://themall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #         会员服务
        - id: themall-member
          uri: lb://themall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<the>.*), /$\{the}

        #
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**,/renren-fast/**
          filters:
            - RewritePath=/api/?(?<the>.*), /renren-fast/$\{the}


        # 商品详情页
        - id: item
          uri: lb://themall-product
          predicates:
            - Path=/item/*.html

        # 商品详情页
        - id: search
          uri: lb://themall-search
          predicates:
            - Path=/list.html

        # 首页
        - id: host
          uri: lb://themall-product
          predicates:
            - Path=/

