#是一次部署
kind: Deployment
apiVersion: apps/v1
metadata:
  #和服务名一致
  name: themall-auth-server
  #属于哪个名称空间
  namespace: themall
  labels:
    #类似HTML的id，下面都是操作这个app
    app: themall-auth-server
    version: v1

spec:
  #副本数
  replicas: 1
  #给谁设置副本
  selector:
    matchLabels:
      app: themall-auth-server
      version: v1
      #模板
  template:
    metadata:
      labels:
        app: themall-auth-server
        version: v1
        #规格
    spec:
      #容器
      containers:
        - name: themall-auth-server
          #设置动态
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          #暴露端口
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          #            - name: tcp-8858
          #              containerPort: 8858
          #              protocol: TCP
          #申请资源
          resources:
            #限制
            limits:
              cpu: 1000m
              memory: 500Mi
            #初始资源
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          #镜像拉取策略 镜像不存在才拉取
          imagePullPolicy: IfNotPresent
          #自动启动
      restartPolicy: Always
      #停机秒数
      terminationGracePeriodSeconds: 30
  #策略
  strategy:
    #滚动更新策略 -> 停一个起一个的更新
    type: RollingUpdate
    rollingUpdate:
      #最大不可用 最多让总共集群的25%不可用，升级的时候最多让25%先不可用
      maxUnavailable: 25%
      #最大存活 更新期间最大允许25%使用
      maxSurge: 25%
      #保留最多10个历史版本
  revisionHistoryLimit: 10
  #最多600秒没有启动成功，就认为卡住了
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: themall-auth-server
  namespace: themall
  labels:
    app: themall-auth-server
    version: v1
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      #Service的端口
      port: 8080
      #容器端口
      targetPort: 8080
      #外部端口
      nodePort: 20002
  selector:
    app: themall-auth-server
  type: NodePort
  sessionAffinity: None
